# Generated by Django 5.2 on 2025-04-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default='india@gmail.com', max_length=254),
        ),
    ]
